# Generated by Django 6.0.2 on 2026-03-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_djapplication_bio_djapplication_dj_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djapplication',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_payment', max_length=20),
        ),
    ]
