# Generated by Django 6.0.2 on 2026-03-08 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_djapplication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_dj', models.BooleanField(default=False)),
                ('source', models.CharField(default='homepage', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_active_at',
        ),
        migrations.AddField(
            model_name='djprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='custom_storage_quota_mb',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='is_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='is_pan_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='onboarding_step',
            field=models.CharField(default='profile_setup', max_length=50),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='overage_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='upi_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pro_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pro_grace_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pro_plan_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pro_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pro_trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='accounts.djprofile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='storage_quota_mb',
            field=models.BigIntegerField(default=3072),
        ),
        migrations.CreateModel(
            name='AmbassadorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('referral_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ambassador_code', to='accounts.djprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DJAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='accounts.djprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('ip', 'IP Address'), ('cidr', 'CIDR Range'), ('device', 'Device Fingerprint')], max_length=10)),
                ('value', models.CharField(max_length=100)),
                ('reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_ips', to='accounts.profile')),
            ],
            options={
                'unique_together': {('type', 'value')},
            },
        ),
    ]
