# Generated by Django 6.0.2 on 2026-03-08 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_missing_items_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='djprofile',
            name='ad_floor_cpm',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='djprofile',
            name='weekly_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DJPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='accounts.djprofile')),
            ],
        ),
    ]
