# Generated by Django 5.2.16 on 2026-09-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_push_ab_testing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="djprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("pending_payment", "Awaiting application fee"),
                    ("pending_review", "Pending review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("banned", "Banned"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
