# Generated by Django 5.2.17 on 2026-09-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_djprofile_status_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="djprofile",
            name="banner_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
