# Generated by Django 5.2.17 on 2026-09-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_djprofile_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="djprofile",
            name="application_links",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
