# Generated by Django 5.2.17 on 2026-09-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("albums", "0002_albumpack_converted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="albumpack",
            name="compare_at_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="albumpack",
            name="copies_limit",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
