# Generated by Django 6.0.2 on 2026-03-03 08:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('file_key', models.CharField(max_length=500)),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True)),
                ('duration_sec', models.IntegerField(blank=True, null=True)),
                ('bpm', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('preview_type', models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('instagram', 'Instagram Reel')], max_length=20, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='accounts.djprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TrackPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_type', models.CharField(choices=[('youtube', 'YouTube'), ('instagram_reel', 'Instagram Reel')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('embed_id', models.CharField(max_length=255)),
                ('embed_html', models.TextField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='tracks.track')),
            ],
        ),
        migrations.CreateModel(
            name='TrackVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_label', models.CharField(max_length=100)),
                ('file_key', models.CharField(max_length=500)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tracks.track')),
            ],
        ),
        migrations.CreateModel(
            name='TrackCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='accounts.djprofile')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='tracks.track')),
            ],
            options={
                'unique_together': {('track', 'dj')},
            },
        ),
    ]
