# Generated by Django 5.1 on 2026-03-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['is_active', 'is_deleted'], name='tracks_trac_is_acti_f0fe18_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['created_at'], name='tracks_trac_created_27a10d_idx'),
        ),
    ]
