# Generated by Django 5.2.16 on 2026-09-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0004_track_converted_at_track_external_link_broken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="source_type",
            field=models.CharField(
                blank=True,
                choices=[("gdrive", "Google Drive"), ("mediafire", "MediaFire"), ("other", "Other")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="DJ-supplied backend file link (Drive/MediaFire). Staff-only, never serialized.",
                max_length=1000,
                null=True,
            ),
        ),
    ]
