# Generated by Django 5.2.16 on 2026-09-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0005_track_source_type_track_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="file_key",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
