# Generated by Django 5.2.17 on 2026-09-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0006_alter_track_file_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="track",
            name="file_format",
            field=models.CharField(
                choices=[
                    ("wav", "WAV (Lossless)"),
                    ("mp3", "MP3 (320kbps)"),
                    ("studio", "Studio Project (ZIP)"),
                    ("aiff", "AIFF"),
                    ("flac", "FLAC"),
                ],
                default="wav",
                max_length=20,
            ),
        ),
    ]
