# Generated by Django 6.0.2 on 2026-03-03 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('content_id', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(choices=[('track', 'Track'), ('album', 'Album')], max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('ip_address', 'content_id', 'content_type')},
            },
        ),
        migrations.CreateModel(
            name='DownloadInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=20)),
                ('insurance_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('claimed', 'Claimed')], default='active', max_length=20)),
                ('claims_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='commerce.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_insurances', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('attempt_number', models.IntegerField(default=1)),
                ('completed', models.BooleanField(default=False)),
                ('checksum_verified', models.BooleanField(default=False)),
                ('bytes_delivered', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('token', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('content_id', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(choices=[('track', 'Track'), ('album', 'Album')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('access_source', models.CharField(max_length=50)),
                ('download_completed', models.BooleanField(default=False)),
                ('bytes_expected', models.BigIntegerField(blank=True, null=True)),
                ('bytes_delivered', models.BigIntegerField(blank=True, null=True)),
                ('checksum_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_tokens', to='accounts.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='downloads_d_token_2778ff_idx'), models.Index(condition=models.Q(('is_used', False)), fields=['expires_at'], name='idx_download_tokens_expiry')],
            },
        ),
    ]
