# Generated by Django 6.0.2 on 2026-03-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlog',
            name='checksum_hex',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='downloadtoken',
            name='checksum_hex',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
