# Generated by Django 5.2.16 on 2026-09-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloads", "0002_downloadlog_checksum_hex_downloadtoken_checksum_hex"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadtoken",
            name="cached_file_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="downloadtoken",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="downloadtoken",
            name="is_expired",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="downloadtoken",
            name="max_downloads",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
