# Generated by Django 5.2.16 on 2026-09-27 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_djprofile_status_choices"),
        ("downloads", "0003_downloadtoken_cached_file_path_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="downloadattempt",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="downloadattempt",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="download_attempts",
                to="accounts.profile",
            ),
        ),
        migrations.AlterField(
            model_name="downloadinsurance",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Awaiting payment"),
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("claimed", "Claimed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="downloadattempt",
            unique_together={("user", "ip_address", "content_id", "content_type")},
        ),
    ]
