# Generated by Django 6.0.2 on 2026-03-08 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_missing_items_update'),
        ('commerce', '0002_purchase_commerce_pu_payment_76df54_idx_and_more'),
        ('tracks', '0003_missing_items_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BundlePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_payment_id', models.CharField(max_length=255)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dj_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BundleTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EarningsHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('hold_type', models.CharField(choices=[('legal_review', 'Legal Review'), ('chargeback', 'Chargeback'), ('dispute', 'Dispute'), ('fraud_investigation', 'Fraud Investigation'), ('admin_manual', 'Admin Manual')], max_length=30)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('forfeited', 'Forfeited')], default='active', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProSubscriptionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('plan_type', models.CharField(max_length=10)),
                ('amount_paise', models.IntegerField()),
                ('gateway', models.CharField(default='phonepe', max_length=20)),
                ('gateway_order_id', models.CharField(max_length=100)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('is_automated', models.BooleanField(default=False)),
                ('eligible_for_auto_refund', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageOverage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_month', models.DateField()),
                ('usage_bytes', models.BigIntegerField()),
                ('overage_bytes', models.BigIntegerField()),
                ('amount_paise', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('gateway_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('reviewed', models.BooleanField(default=False)),
                ('outcome', models.CharField(blank=True, choices=[('safe', 'Safe'), ('frozen', 'Frozen'), ('refunded_blocked', 'Refunded & Blocked')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(max_length=50)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='commerce_pu_payment_76df54_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='commerce_pu_payment_da4968_idx',
        ),
        migrations.AddField(
            model_name='purchase',
            name='amount_paise',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='gateway_refund_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='gateway_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='has_download_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_escrow_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchase',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_gateway',
            field=models.CharField(default='phonepe', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='content_type',
            field=models.CharField(choices=[('track', 'Track'), ('album', 'Album'), ('bundle', 'Bundle')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['gateway_payment_id'], name='commerce_pu_gateway_82a738_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['gateway_order_id'], name='commerce_pu_gateway_2b804c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', 'status'], name='commerce_pu_user_id_f8898f_idx'),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_audit_logs', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='adminauditlog',
            name='target_dj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_targeted', to='accounts.djprofile'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='dj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='accounts.djprofile'),
        ),
        migrations.AddField(
            model_name='bundlepurchase',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='commerce.bundle'),
        ),
        migrations.AddField(
            model_name='bundlepurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_purchases', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='bundletrack',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_tracks', to='commerce.bundle'),
        ),
        migrations.AddField(
            model_name='bundletrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.track'),
        ),
        migrations.AddField(
            model_name='earningshold',
            name='dj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_holds', to='accounts.djprofile'),
        ),
        migrations.AddField(
            model_name='earningshold',
            name='placed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holds_placed', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='earningshold',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holds_resolved', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='prosubscriptionevent',
            name='dj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_events', to='accounts.djprofile'),
        ),
        migrations.AddField(
            model_name='purchasedispute',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='commerce.purchase'),
        ),
        migrations.AddField(
            model_name='purchasedispute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_opened', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_request', to='commerce.purchase'),
        ),
        migrations.AddField(
            model_name='storageoverage',
            name='dj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overages', to='accounts.djprofile'),
        ),
        migrations.AddField(
            model_name='transactionalert',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='commerce.purchase'),
        ),
        migrations.AddField(
            model_name='transactionalert',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tx_alerts', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='transactionalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_alerts', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.track'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='accounts.profile'),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='payment_order_id',
        ),
        migrations.AlterUniqueTogether(
            name='bundletrack',
            unique_together={('bundle', 'track')},
        ),
        migrations.AlterUniqueTogether(
            name='storageoverage',
            unique_together={('dj', 'billing_month')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'track')},
        ),
    ]
