# Generated by Django 6.0.2 on 2026-03-08 11:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_missing_item_02'),
        ('commerce', '0003_missing_items_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='buyer_role',
            field=models.CharField(default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cart_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_applied',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchase',
            name='download_method',
            field=models.CharField(default='mixmint', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='external_link_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OffloadNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_id', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=10)),
                ('reason', models.CharField(default='underperforming', max_length=20)),
                ('storage_mb', models.IntegerField(blank=True, null=True)),
                ('sales_in_period', models.IntegerField(blank=True, null=True)),
                ('period_days', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offload_notifications', to='accounts.djprofile')),
            ],
        ),
    ]
