# Generated by Django 5.1 on 2026-03-14 05:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_missing_item_02"),
        ("commerce", "0005_add_cart_items"),
    ]

    operations = [
        migrations.CreateModel(
            name="DJPromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("description", models.TextField()),
                (
                    "commission_discount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=5
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("max_uses", models.IntegerField(default=100)),
                ("times_used", models.IntegerField(default=0)),
                ("new_djs_only", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DJOnboardingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profile_completed", models.BooleanField(default=False)),
                ("bank_details_added", models.BooleanField(default=False)),
                ("first_track_uploaded", models.BooleanField(default=False)),
                ("pricing_set", models.BooleanField(default=False)),
                ("store_customized", models.BooleanField(default=False)),
                ("completion_percent", models.IntegerField(default=0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_reminder_sent", models.DateTimeField(blank=True, null=True)),
                ("reminders_sent", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dj",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_progress",
                        to="accounts.djprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DJWelcomeBonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50.00"), max_digits=10
                    ),
                ),
                ("credited", models.BooleanField(default=False)),
                ("credited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dj",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welcome_bonus",
                        to="accounts.djprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DJMilestoneReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone",
                    models.CharField(
                        choices=[
                            ("first_track", "First Track Uploaded"),
                            ("first_sale", "First Sale"),
                            ("10_sales", "10 Sales"),
                            ("50_sales", "50 Sales"),
                            ("100_sales", "100 Sales"),
                            ("1000_earnings", "₹1000 Earned"),
                            ("5000_earnings", "₹5000 Earned"),
                            ("10000_earnings", "₹10000 Earned"),
                        ],
                        max_length=50,
                    ),
                ),
                ("reward_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("credited", models.BooleanField(default=False)),
                ("credited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_rewards",
                        to="accounts.djprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("dj", "milestone")},
            },
        ),
        migrations.CreateModel(
            name="DJPromoApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_discount",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "dj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promo_applications",
                        to="accounts.djprofile",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commerce.djpromocode",
                    ),
                ),
            ],
            options={
                "unique_together": {("dj", "promo")},
            },
        ),
        migrations.CreateModel(
            name="DJReferralProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referral_code", models.CharField(max_length=20)),
                (
                    "referrer_bonus",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=10
                    ),
                ),
                (
                    "referred_bonus",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("50.00"), max_digits=10
                    ),
                ),
                ("referrer_paid", models.BooleanField(default=False)),
                ("referred_paid", models.BooleanField(default=False)),
                ("first_sale_achieved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "referred",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referred_by",
                        to="accounts.djprofile",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to="accounts.djprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("referrer", "referred")},
            },
        ),
    ]
