# Generated by Django 5.2.16 on 2026-09-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0008_fix_beat_task_paths"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                    ("transfer", "Escrow transfer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                    ("disputed", "Disputed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
