# Generated by Django 5.2.17 on 2026-09-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0009_ledger_transfer_purchase_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="bundle",
            name="cover_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
