# Generated by Django 5.2.17 on 2026-10-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0010_catalog_upgrades"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="failure_reason",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="provider",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="payout",
            name="provider_ref",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="payout",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="utr",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
