# Generated by Django 6.0.2 on 2026-03-03 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('admin_panel', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('track', 'Track'), ('album', 'Album/ZIP')], max_length=20)),
                ('content_id', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('file_key', models.CharField(max_length=500)),
                ('reason', models.TextField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('dj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_content', to='accounts.djprofile')),
            ],
        ),
    ]
