# Generated by Django 6.0.2 on 2026-03-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_contentarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_commission_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('buyer_platform_fee_enabled', models.BooleanField(default=False)),
                ('buyer_platform_fee', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('gst_charging_enabled', models.BooleanField(default=False)),
                ('dj_application_fee_enabled', models.BooleanField(default=False)),
                ('dj_application_fee', models.DecimalField(decimal_places=2, default=99.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255)),
                ('sub_text', models.CharField(blank=True, max_length=255, null=True)),
                ('badge_label', models.CharField(default='LIMITED TIME', max_length=50)),
                ('occasion_tag', models.CharField(default='Launch', max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('show_on_navbar', models.BooleanField(default=True)),
                ('show_on_dj_upload', models.BooleanField(default=True)),
                ('show_on_checkout', models.BooleanField(default=True)),
                ('show_on_track_pages', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
