# Generated by Django 6.0.2 on 2026-03-08 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_missing_item_02'),
        ('admin_panel', '0005_platformsettings_promotionaloffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancemode',
            name='estimated_return_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('track', 'Track'), ('album', 'Album')], max_length=20)),
                ('content_id', models.PositiveBigIntegerField()),
                ('report_type', models.CharField(choices=[('copyright', 'Copyright Infringement'), ('spam', 'Spam / Misleading'), ('audio', 'Bad Audio Quality'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to='accounts.profile')),
            ],
        ),
    ]
