# Generated by Django 5.1 on 2026-03-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0007_platformsettings_offload_low_sales_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fraudalert",
            name="admin_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fraudalert",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fraudalert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("download_farming", "Download Farming"),
                    ("payment_fraud", "Payment Fraud"),
                    ("suspicious_activity", "Suspicious Activity"),
                    ("ip_abuse", "IP Abuse"),
                    ("ip_spoofing", "IP Spoofing"),
                    ("rate_limit_exceeded", "Rate Limit Exceeded"),
                ],
                max_length=50,
            ),
        ),
    ]
