# Generated by Django 5.2.16 on 2026-09-22 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_push_ab_testing"),
        ("admin_panel", "0008_dj_conversion_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionaloffer",
            name="dj",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="accounts.djprofile",
            ),
        ),
    ]
