# Generated by Django 5.2.17 on 2026-09-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0010_support_threads"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="tg_singles_channel_id",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="tg_singles_channel_title",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="tg_zips_channel_id",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="tg_zips_channel_title",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="vault_evict_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="vault_hold_days",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="platformsettings",
            name="vault_rehold_days",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.CreateModel(
            name="VaultFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[("track", "Track"), ("album", "Album")], max_length=10
                    ),
                ),
                ("content_id", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Copying to channel"),
                            ("archived", "Stored in channel"),
                            ("too_large", "Too big for the bot (R2 only)"),
                            ("failed", "Failed"),
                        ],
                        default="failed",
                        max_length=12,
                    ),
                ),
                ("channel_id", models.CharField(blank=True, default="", max_length=40)),
                ("message_id", models.BigIntegerField(blank=True, null=True)),
                ("file_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "file_unique_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("file_key", models.CharField(blank=True, default="", max_length=500)),
                ("error", models.CharField(blank=True, default="", max_length=255)),
                ("restored_count", models.PositiveIntegerField(default=0)),
                ("r2_present", models.BooleanField(default=True)),
                ("r2_hold_until", models.DateTimeField(blank=True, null=True)),
                ("evicted_at", models.DateTimeField(blank=True, null=True)),
                ("job_id", models.CharField(blank=True, default="", max_length=64)),
                ("job_started_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status"], name="admin_panel_status_b1832e_idx"
                    )
                ],
                "unique_together": {("content_type", "content_id")},
            },
        ),
    ]
