# Generated by Django 5.2.17 on 2026-10-01 16:02

import django.db.models.deletion
from django.db import migrations, models


def hold_30_days(apps, schema_editor):
    """Files now stay in R2 for 30 days after upload (was 10), unless the admin already changed it."""
    apps.get_model('admin_panel', 'PlatformSettings').objects.filter(vault_hold_days=10).update(vault_hold_days=30)
    VaultFile = apps.get_model('admin_panel', 'VaultFile')
    from datetime import timedelta
    for rec in VaultFile.objects.filter(r2_present=True, r2_hold_until__isnull=False):
        rec.r2_hold_until = rec.r2_hold_until + timedelta(days=20)
        rec.save(update_fields=['r2_hold_until'])



class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_catalog_upgrades"),
        ("admin_panel", "0011_telegram_vault"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="tg_mtproto_session",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="platformsettings",
            name="vault_hold_days",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name="TelegramLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.CharField(max_length=40)),
                ("username", models.CharField(blank=True, default="", max_length=64)),
                ("linked_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_link",
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VaultNotify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content_type", models.CharField(max_length=10)),
                ("content_id", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vault_waits",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["content_type", "content_id", "notified_at"],
                        name="admin_panel_content_762e5c_idx",
                    )
                ],
            },
        ),        migrations.RunPython(hold_30_days, migrations.RunPython.noop),
    ]
