# Generated by Django 5.2.17 on 2026-10-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0011_telegram_vault"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="tg_mtproto_session",
            field=models.TextField(blank=True, default=""),
        ),
    ]
