# Generated by Django 5.2.17 on 2026-10-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0012_vault_mtproto"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformsettings",
            name="cart_discounts_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
