# Generated by Django 5.2.17 on 2026-10-02 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_catalog_upgrades"),
        ("admin_panel", "0013_cart_discounts_switch"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentreport",
            name="evidence_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="reporter_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="reporter_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="contentreport",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_sent",
                to="accounts.profile",
            ),
        ),
    ]
